import express from "express";
import cors from "cors";
import path from "path";
import { pool } from "./db";
import { OfferService } from "./offer.service";
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, "..", "public")));
app.post("/offer/publish", async (req, res) => { const r = await OfferService.publishOffer(req.body); res.status(r.ok ? 200 : 400).json(r); });
app.post("/offer/update", async (req, res) => { const r = await OfferService.updateOffer(req.body); res.status(r.ok ? 200 : 400).json(r); });
app.post("/offer/withdraw", async (req, res) => { const r = await OfferService.withdrawOffer(req.body.offerId); res.status(r.ok ? 200 : 400).json(r); });
app.get("/offers", async (_req, res) => { const r = await pool.query(`SELECT offer_id, state, price, volume, metal, last_version FROM projection.offers_state ORDER BY last_version DESC`); res.json({ ok: true, offers: r.rows }); });
app.listen(3000, () => console.log("API running on http://localhost:3000"));
